export { default as ProductListPage } from "./ProductListPage";
export { default as AddProductPage } from "./AddProductPages";
export { default as CustomerListPage } from "./CustomerListPage";
export { default as AddCustomerPage } from "./AddCustomerPage";
export { default as DeletedProductListPage } from "./DeletedProductListPage";
export { default as DeletedCustomerListPage } from "./DeletedCustomerListPage";
export { default as TaxListPage } from "./TaxListPage";
export { default as AddTaxPage } from "./AddTaxPage";
export { default as SideBar } from "./SideBar";
